# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false
# Изменяет текущую временную зону.
before_install:
  - export TZ=Europe/Moscow
  - date
# Sqlite
  adapter: sqlite3
  database: ":./db/parser:"
  timeout: 500
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - rusanov_roman@icloud.com
    on_success: never # default: change
    on_failure: always # default: always